version: '3.8'
services:
  frontend:
    build: ./apps/frontend
    ports:
      - '3000:3000'
    env_file:
      - .env
  admin-dashboard:
    build: ./apps/admin-dashboard
    ports:
      - '3001:3000'
    env_file:
      - .env
  mobile:
    build: ./apps/mobile
    ports:
      - '8081:8081'
    env_file:
      - .env
  agent-api:
    build: ./services/agent-api
    ports:
      - '4000:4000'
    env_file:
      - .env
  gateway:
    build: ./apps/gateway
    ports:
      - '4001:4000'
    env_file:
      - .env

